print("nomecompleto")
print("V:1.0")
print("digite o primeiro nome")
nome = input()
print("digite os sobrenomes")
sobre = input()
linha = "O seu nome completo é %s %s" % (nome, sobre)
print (linha)
input("Pressione enter para sair")